### ISSUE TITLE
Hello there can u pls add asian shows in this app that can be downloaded in different qualities from 360 p? This would b great thanks 😊 

### ISSUE THREAD

**Issue by Aruraka** [Moeefa/anime-app#2]

**Comment by lxinaider** [comment]
I'll take a look, if I find a provider to include this, I will definitely do so, thanks for the suggestion!
I'll try to keep you updated on the progress of this feature here whenever possible, as I've already been working on an update for the app.

**Comment by Aruraka** [comment]
I can suggest u some providers which have asian dramas: 1)https://kissasian.boo/2)https://www2.newasiantv.pro/
These providers have all asian dramas

**Comment by lxinaider** [comment]
> I can suggest u some providers which have asian dramas: 1)https://kissasian.boo/2)https://www2.newasiantv.pro/ These providers have all asian dramas

The only problem with websites like these is that they're obfucasted and it's pretty difficult to scrap them:
![image](https://github.com/user-attachments/assets/6b1f7410-aa31-416b-8187-6d4baaa9c21d)
I'll look at alternative websites to scrap them or deobfuscate them in some way.
I'm short on time lately, so this might take a while.

**Comment by Aruraka** [comment]
> > I can suggest u some providers which have asian dramas: 1)https://kissasian.boo/2)https://www2.newasiantv.pro/ These providers have all asian dramas
> 
> The only problem with websites like these is that they're obfucasted and it's pretty difficult to scrap them: ![image](https://private-user-images.githubusercontent.com/32604322/355676968-6b1f7410-aa31-416b-8187-6d4baaa9c21d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTM2MTUsIm5iZiI6MTcyMzAxMzMxNSwicGF0aCI6Ii8zMjYwNDMyMi8zNTU2NzY5NjgtNmIxZjc0MTAtYWEzMS00MTZiLTgxODctNmQ0YmFhYTljMjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA2NDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOTY3YzhhMTE4MzAyM2Q1NmZkOGVhMjRkYzIxNGQ1ODcwYzEwOGQzMjg4NmY3ZmNiN2U5Mjk1MjlhM2E0MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._uQzXZ0n-ep6YW0Wrf9p7rminV1Hf4jEGgOs4oatrmo) I'll look at alternative websites to scrap them or deobfuscate them in some way. I'm short on time lately, so this might take a while.

Oh that's okay ..I could suggest u dramacool but while downloading from dramacool videos r appearing blank that's why I'm not suggesting it

**Comment by lxinaider** [comment]
Getting some progress on scraping Dramacool, found out there's some scrapers available on Github that actually does the extraction of the streaming URL decrypting the parameters and etc from the video provider, this makes scraping much easier.
![image](https://github.com/user-attachments/assets/be1247e6-078a-4bdb-94cf-04b4a864c653)

**Comment by Aruraka** [comment]
> Getting some progress on scraping Dramacool, found out there's some scrapers available on Github that actually does the extraction of the streaming URL decrypting the parameters and etc from the video provider, this makes scraping much easier. ![image](https://private-user-images.githubusercontent.com/32604322/355868382-be1247e6-078a-4bdb-94cf-04b4a864c653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDUyNDksIm5iZiI6MTcyMzA0NDk0OSwicGF0aCI6Ii8zMjYwNDMyMi8zNTU4NjgzODItYmUxMjQ3ZTYtMDc4YS00YmRiLTk0Y2YtMDRiNGE4NjRjNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE1MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MTQyOTkyNDU3MzliMGE4Mjk0NjhlNWUyNDU3ZDM1MzNiODVmYjY0YWEyYWEyMjljMzdhNTVkYmY4OGJlOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ax9B0SospitLKHYk21WKQqgru40xR-QVgWg1slf0LUk)

Ah that's nice but most videos in dramacool r blank after downloading from dramacool website..I faced this problem

**Comment by Aruraka** [comment]
> Getting some progress on scraping Dramacool, found out there's some scrapers available on Github that actually does the extraction of the streaming URL decrypting the parameters and etc from the video provider, this makes scraping much easier. ![image](https://private-user-images.githubusercontent.com/32604322/355868382-be1247e6-078a-4bdb-94cf-04b4a864c653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDg5MTcsIm5iZiI6MTcyMzA0ODYxNywicGF0aCI6Ii8zMjYwNDMyMi8zNTU4NjgzODItYmUxMjQ3ZTYtMDc4YS00YmRiLTk0Y2YtMDRiNGE4NjRjNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE2MzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZTg0ZDI3OTM5ZDIxMGU2ZDQxOGUyNDk4ODkzNTVlZjQ4MTlmOTc5YjYzODQ1OTIzMTg0YTNiMTFjYzgxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yA9W1yzg-w0SRaUj8sDDR4hjReJoNpFouh0pHyMnR7A)

U can do another thing..I found this website which have all dramas .."asianload"..website..u can try to scrap from that website too

**Comment by lxinaider** [comment]
> > Getting some progress on scraping Dramacool, found out there's some scrapers available on Github that actually does the extraction of the streaming URL decrypting the parameters and etc from the video provider, this makes scraping much easier. ![image](https://private-user-images.githubusercontent.com/32604322/355868382-be1247e6-078a-4bdb-94cf-04b4a864c653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDUyNDksIm5iZiI6MTcyMzA0NDk0OSwicGF0aCI6Ii8zMjYwNDMyMi8zNTU4NjgzODItYmUxMjQ3ZTYtMDc4YS00YmRiLTk0Y2YtMDRiNGE4NjRjNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE1MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MTQyOTkyNDU3MzliMGE4Mjk0NjhlNWUyNDU3ZDM1MzNiODVmYjY0YWEyYWEyMjljMzdhNTVkYmY4OGJlOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ax9B0SospitLKHYk21WKQqgru40xR-QVgWg1slf0LUk)
> 
> Ah that's nice but most videos in dramacool r blank after downloading from dramacool website..I faced this problem

![image](https://github.com/user-attachments/assets/0f2fccbf-2e34-421d-aee8-c260293b8217)
I managed to scrap the video and seems to work fine for now.

> > Getting some progress on scraping Dramacool, found out there's some scrapers available on Github that actually does the extraction of the streaming URL decrypting the parameters and etc from the video provider, this makes scraping much easier. ![image](https://private-user-images.githubusercontent.com/32604322/355868382-be1247e6-078a-4bdb-94cf-04b4a864c653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDg5MTcsIm5iZiI6MTcyMzA0ODYxNywicGF0aCI6Ii8zMjYwNDMyMi8zNTU4NjgzODItYmUxMjQ3ZTYtMDc4YS00YmRiLTk0Y2YtMDRiNGE4NjRjNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE2MzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZTg0ZDI3OTM5ZDIxMGU2ZDQxOGUyNDk4ODkzNTVlZjQ4MTlmOTc5YjYzODQ1OTIzMTg0YTNiMTFjYzgxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yA9W1yzg-w0SRaUj8sDDR4hjReJoNpFouh0pHyMnR7A)
> 
> U can do another thing..I found this website which have all dramas .."asianload"..website..u can try to scrap from that website too

It seems that Dramacool website uses Asianload as provider, but I'll take a look over it.

**Comment by Aruraka** [comment]
> > > Getting some progress on scraping Dramacool, found out there's some scrapers available on Github that actually does the extraction of the streaming URL decrypting the parameters and etc from the video provider, this makes scraping much easier. ![image](https://private-user-images.githubusercontent.com/32604322/355868382-be1247e6-078a-4bdb-94cf-04b4a864c653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDUyNDksIm5iZiI6MTcyMzA0NDk0OSwicGF0aCI6Ii8zMjYwNDMyMi8zNTU4NjgzODItYmUxMjQ3ZTYtMDc4YS00YmRiLTk0Y2YtMDRiNGE4NjRjNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE1MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MTQyOTkyNDU3MzliMGE4Mjk0NjhlNWUyNDU3ZDM1MzNiODVmYjY0YWEyYWEyMjljMzdhNTVkYmY4OGJlOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ax9B0SospitLKHYk21WKQqgru40xR-QVgWg1slf0LUk)
> > 
> > 
> > Ah that's nice but most videos in dramacool r blank after downloading from dramacool website..I faced this problem
> 
> ![image](https://private-user-images.githubusercontent.com/32604322/356081184-0f2fccbf-2e34-421d-aee8-c260293b8217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDY3NDgsIm5iZiI6MTcyMzEwNjQ0OCwicGF0aCI6Ii8zMjYwNDMyMi8zNTYwODExODQtMGYyZmNjYmYtMmUzNC00MjFkLWFlZTgtYzI2MDI5M2I4MjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA4NDA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MGY2Yjk5ODhiMzdlMDZlMDg4ZmUwZDAzZDA3MzkyZjA2ZWRhYTQzNDkxYTFmODg0ZTczZGM1MzAwOTI4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xvP_OUYkQ6EbM_VfPC8Lsg7vhVMzlTcUOwkzmn-pVdU) I managed to scrap the video and seems to work fine for now.
> 
> > > Getting some progress on scraping Dramacool, found out there's some scrapers available on Github that actually does the extraction of the streaming URL decrypting the parameters and etc from the video provider, this makes scraping much easier. ![image](https://private-user-images.githubusercontent.com/32604322/355868382-be1247e6-078a-4bdb-94cf-04b4a864c653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDg5MTcsIm5iZiI6MTcyMzA0ODYxNywicGF0aCI6Ii8zMjYwNDMyMi8zNTU4NjgzODItYmUxMjQ3ZTYtMDc4YS00YmRiLTk0Y2YtMDRiNGE4NjRjNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE2MzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZTg0ZDI3OTM5ZDIxMGU2ZDQxOGUyNDk4ODkzNTVlZjQ4MTlmOTc5YjYzODQ1OTIzMTg0YTNiMTFjYzgxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yA9W1yzg-w0SRaUj8sDDR4hjReJoNpFouh0pHyMnR7A)
> > 
> > 
> > U can do another thing..I found this website which have all dramas .."asianload"..website..u can try to scrap from that website too
> 
> It seems that Dramacool website uses Asianload as provider, but I'll take a look over it.

Okay sure thanks :))

**Comment by Aruraka** [comment]
Btw do u have discord?

**Comment by lxinaider** [comment]
> Btw do u have discord?

Sure, just send me a friend request: @moeefa

**Comment by Aruraka** [comment]
> > Btw do u have discord?
> 
> Sure, just send me a friend request: @Moeefa

Hii btw I haven't found ur discord after I clicked on discord link..Can u share ur discord id?

**Comment by lxinaider** [comment]
Here it is: 482224256730791967

**Comment by Aruraka** [comment]
> Here it is: 482224256730791967

Btw it's only numbers tho😅I still couldn't find it..here is mine.. arundhati_2024

**Comment by lxinaider** [comment]
> > Here it is: 482224256730791967
> 
> Btw it's only numbers tho😅I still couldn't find it..here is mine.. arundhati_2024

Oh, @moeefa was my ID then, sent you a request.

**Comment by lxinaider** [comment]
Closing this issue as [9b47e57](https://github.com/Moeefa/anime-app/commit/9b47e57a6478c9708bfb059499bb72d04cae7cfb) add the Dramacool provider. 😊
